top = "<!DOCTYPE html>\n<html>\n<head>\n<style>\nbody {\ntext-align: center;\nfont-family: sans-serif;\n}\n</style>\n</head>\n<body>\n<h1>Doug's birthday list</h1>\n<hr>\n<h2>ONLY BUY ITEMS FROM THE LINKS ON THE LIST!</h2>"
bottom = "<hr>\n</body>\n</html>\n"
body = ""
items = [["Headphones","https://www.microcenter.com/product/646597/audio-technica-ath-gdl3-high-fidelity-open-back-gaming-headset-black"],["Portal 1 and 2 (or a $20 steam gift card)","https://store.steampowered.com/app/400/Portal/"],["Yamaha MG06X Mixer OR (see next in list)","https://www.amazon.com/YAMAHA-MG06X-Discrete-Compressors-Studio-Quality/dp/B00I2J4V5G"],["Yamaha MG10X mixer","https://www.amazon.com/MG10XU-10-Channel-Microphone-Dedicated-Compressors/dp/B0C1VZR99C"],["Audio adapters","https://www.amazon.com/Cable-Matters-5-Pack-Plated-Adapter/dp/B00PIWB2SO"],["A radio HAT for Raspberry Pi","https://www.amazon.com/SX1262-LoRa-HAT-Raspberry-Communication/dp/B0822Z3CX8"],["DigiRig Base Unit (YOU MUST BUY THE DIGIRIG CABLES IF YOU BUY THIS!)","https://www.amazon.com/Digirig-Mobile-Integrated-Digital-Interface/dp/B095B9C15R"],["DigiRig Cables (BUY THIS WITH THE DIGIRIG BASE UNIT!)","https://www.amazon.com/Digirig-Mobile-Integrated-Digital-Interface/dp/B095B9C15R"],["Antenna Tuner (for my radio)","https://www.hamradio.com/detail.cfm?pid=H0-009809"],["Desk Microphone (OR see next)","https://www.hamradio.com/detail.cfm?pid=H0-011024"],["The OTHER desk mic","https://www.hamradio.com/detail.cfm?pid=H0-018852"],["Possible new soldering iron?","https://www.microcenter.com/product/680474/weller-digital-soldering-station-with-70w-precision-iron"],["Sound card","https://www.microcenter.com/product/710288/creative-labs-sound-blaster-audigy-fx-pro-hi-res-71-pci-e-sound-card"],["Yet another desk mic (this time for my computer)","https://www.microcenter.com/product/628543/elgato-wave-3-usb-condenser-microphone-black"],["Audio cables","https://www.microcenter.com/product/707495/ppa-35-mm-to-35-mm-stereo-audio-braided-cable-6-ft-black-white"]]

for item in items:
    body = body + f"<hr>\n<h2>{item[0]}</h2>\n<h3><a target=\"_blank\" href=\"{item[1]}\">Link</a></h3>\n"

with open("index.html","w") as index:
    index.write(top + body + bottom)